version: '3.8'

services:
  mysql-test-database:
    image: mysql:latest
    container_name: mysql-test-database
    expose:
      - 3346
    ports:
      - 3346:3306
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ~/.test_data:/var/lib/mysql